In [1]:
import sys, os
sys.path.append(os.path.abspath(".."))

%load_ext autoreload
%autoreload 2

import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
from sqlalchemy import text
from src.db import engine

with open("../sql/analytics_queries/01_championship_progression.sql") as f:
    query = f.read()

result_df = pd.read_sql(text(query), engine)
result_df.head(20)

,forename,surname,year,round,race_date,points,cumulative_points,championship_rank_after_race
0,Max,Verstappen,2023,1,2023-03-05,25.0,25.0,1
1,Sergio,Pérez,2023,1,2023-03-05,18.0,18.0,2
2,Fernando,Alonso,2023,1,2023-03-05,15.0,15.0,3
3,Carlos,Sainz,2023,1,2023-03-05,12.0,12.0,4
4,Lewis,Hamilton,2023,1,2023-03-05,10.0,10.0,5
5,Lance,Stroll,2023,1,2023-03-05,8.0,8.0,6
6,George,Russell,2023,1,2023-03-05,6.0,6.0,7
7,Valtteri,Bottas,2023,1,2023-03-05,4.0,4.0,8
8,Pierre,Gasly,2023,1,2023-03-05,2.0,2.0,9
9,Alexander,Albon,2023,1,2023-03-05,1.0,1.0,10
10,Oscar,Piastri,2023,1,2023-03-05,0.0,0.0,11
11,Yuki,Tsunoda,2023,1,2023-03-05,0.0,0.0,11
12,Esteban,Ocon,2023,1,2023-03-05,0.0,0.0,11
13,Guanyu,Zhou,2023,1,2023-03-05,0.0,0.0,11
14,Charles,Leclerc,2023,1,2023-03-05,0.0,0.0,11
15,Kevin,Magnussen,2023,1,2023-03-05,0.0,0.0,11
16,Logan,Sargeant,2023,1,2023-03-05,0.0,0.0,11
17,Nico,Hülkenberg,2023,1,2023-03-05,0.0,0.0,11
18,Nyck,de Vries,2023,1,2023-03-05,0.0,0.0,11
19,Lando,Norris,2023,1,2023-03-05,0.0,0.0,11

In [3]:
import os
print("Current working directory:", os.getcwd())
print("Does src exist one level up?", os.path.exists(os.path.abspath("../src")))

Current working directory: c:\Users\tanus\Music\F1-analytics\notebooks
Does src exist one level up? True

In [4]:
status_check = pd.read_sql("SELECT * FROM dim_status ORDER BY status_id", engine)
print(status_check.to_string())

     status_key  status_id              status
0             1          1            Finished
1             2          2        Disqualified
2             3          3            Accident
3             4          4           Collision
4             5          5              Engine
5             6          6             Gearbox
6             7          7        Transmission
7             8          8              Clutch
8             9          9          Hydraulics
9            10         10          Electrical
10           11         11              +1 Lap
11           12         12             +2 Laps
12           13         13             +3 Laps
13           14         14             +4 Laps
14           15         15             +5 Laps
15           16         16             +6 Laps
16           17         17             +7 Laps
17           18         18             +8 Laps
18           19         19             +9 Laps
19           20         20            Spun off
20           21         21            Radiator
21           22         22          Suspension
22           23         23              Brakes
23           24         24        Differential
24           25         25         Overheating
25           26         26          Mechanical
26           27         27                Tyre
27           28         28         Driver Seat
28           29         29            Puncture
29           30         30          Driveshaft
30           31         31             Retired
31           32         32       Fuel pressure
32           33         33          Front wing
33           34         34      Water pressure
34           35         35          Refuelling
35           36         36               Wheel
36           37         37            Throttle
37           38         38            Steering
38           39         39           Technical
39           40         40         Electronics
40           41         41         Broken wing
41           42         42    Heat shield fire
42           43         43             Exhaust
43           44         44            Oil leak
44           45         45            +11 Laps
45           46         46           Wheel rim
46           47         47          Water leak
47           48         48           Fuel pump
48           49         49           Track rod
49           50         50            +17 Laps
50           51         51        Oil pressure
51           53         53            +13 Laps
52           54         54            Withdrew
53           55         55            +12 Laps
54           56         56         Engine fire
55           58         58            +26 Laps
56           59         59       Tyre puncture
57           60         60         Out of fuel
58           61         61           Wheel nut
59           62         62      Not classified
60           63         63          Pneumatics
61           64         64            Handling
62           65         65           Rear wing
63           66         66                Fire
64           67         67       Wheel bearing
65           68         68            Physical
66           69         69         Fuel system
67           70         70            Oil line
68           71         71            Fuel rig
69           72         72      Launch control
70           73         73             Injured
71           74         74                Fuel
72           75         75          Power loss
73           76         76          Vibrations
74           77         77           107% Rule
75           78         78              Safety
76           79         79          Drivetrain
77           80         80            Ignition
78           81         81     Did not qualify
79           82         82              Injury
80           83         83             Chassis
81           84         84             Battery
82           85         85             Stalled
83           86         86           Halfshaft
84           87         87          Crankshaft
85           88         88            +10 Laps
86           89         89     Safety concerns
87           90         90       Not restarted
88           91         91          Alternator
89           92         92         Underweight
90           93         93         Safety belt
91           94         94            Oil pump
92           95         95           Fuel leak
93           96         96            Excluded
94           97         97  Did not prequalify
95           98         98           Injection
96           99         99         Distributor
97          100        100       Driver unwell
98          101        101               Turbo
99          102        102            CV joint
100         103        103          Water pump
101         104        104      Fatal accident
102         105        105         Spark plugs
103         106        106           Fuel pipe
104         107        107          Eye injury
105         108        108            Oil pipe
106         109        109                Axle
107         110        110          Water pipe
108         111        111            +14 Laps
109         112        112            +15 Laps
110         113        113            +25 Laps
111         114        114            +18 Laps
112         115        115            +22 Laps
113         116        116            +16 Laps
114         117        117            +24 Laps
115         118        118            +29 Laps
116         119        119            +23 Laps
117         120        120            +21 Laps
118         121        121             Magneto
119         122        122            +44 Laps
120         123        123            +30 Laps
121         124        124            +19 Laps
122         125        125            +46 Laps
123         126        126        Supercharger
124         127        127            +20 Laps
125          52        128            +42 Laps
126          57        129      Engine misfire
127         128        130    Collision damage
128         129        131          Power Unit
129         130        132                 ERS
130         131        133            +49 Laps
131         132        134            +38 Laps
132         133        135          Brake duct
133         134        136                Seat
134         135        137              Damage
135         136        138              Debris
136         137        139             Illness
137         138        140           Undertray
138         139        141      Cooling system

In [5]:
with open("../sql/analytics_queries/02_reliability_rate.sql") as f:
    query = f.read()

reliability_df = pd.read_sql(text(query), engine)
reliability_df

,constructor_name,year,total_entries,mechanical_failures,mechanical_failure_rate_pct,accidents,finishes,finish_rate_pct
0,Ferrari,2023,44,5,11.4,2,36,81.8
1,Alpine F1 Team,2023,44,4,9.1,6,34,77.3
2,Alfa Romeo,2023,44,4,9.1,2,38,86.4
3,Williams,2023,44,4,9.1,6,33,75.0
4,Mercedes,2023,44,3,6.8,2,38,86.4
5,Haas F1 Team,2023,44,3,6.8,4,37,84.1
6,Aston Martin,2023,44,3,6.8,2,37,84.1
7,AlphaTauri,2023,44,2,4.5,3,39,88.6
8,McLaren,2023,44,2,4.5,2,40,90.9
9,Red Bull,2023,44,0,0.0,2,42,95.5

In [6]:
with open("../sql/analytics_queries/03_grid_delta.sql") as f:
    query = f.read()

grid_delta_df = pd.read_sql(text(query), engine)
grid_delta_df

,forename,surname,year,races_completed,avg_positions_gained,overtaking_rank
0,Sergio,Pérez,2023,20,2.50,1
1,Max,Verstappen,2023,22,1.91,2
2,Liam,Lawson,2023,5,1.60,3
3,Guanyu,Zhou,2023,21,1.33,4
4,Lance,Stroll,2023,19,1.05,5
5,Daniel,Ricciardo,2023,7,1.00,6
6,Logan,Sargeant,2023,21,0.90,7
7,Yuki,Tsunoda,2023,22,0.64,8
8,Pierre,Gasly,2023,22,0.45,9
9,Nyck,de Vries,2023,9,0.44,10
10,Fernando,Alonso,2023,21,0.14,11
11,Lando,Norris,2023,22,-0.05,12
12,Lewis,Hamilton,2023,22,-0.09,13
13,Alexander,Albon,2023,22,-0.45,14
14,Valtteri,Bottas,2023,21,-0.48,15
15,Esteban,Ocon,2023,21,-0.81,16
16,Kevin,Magnussen,2023,19,-1.00,17
17,Oscar,Piastri,2023,22,-1.27,18
18,George,Russell,2023,22,-1.64,19
19,Carlos,Sainz,2023,22,-1.73,20
20,Charles,Leclerc,2023,21,-2.57,21
21,Nico,Hülkenberg,2023,19,-3.21,22

In [7]:
with open("../sql/analytics_queries/04_rolling_form.sql") as f:
    query = f.read()

rolling_form_df = pd.read_sql(text(query), engine)
rolling_form_df

   forename     surname  round   race_date  points  rolling_5race_form
0       Max  Verstappen      1  2023-03-05    25.0               25.00
1       Max  Verstappen      2  2023-03-19    19.0               22.00
2       Max  Verstappen      3  2023-04-02    25.0               23.00
3       Max  Verstappen      4  2023-04-30    18.0               21.75
4       Max  Verstappen      5  2023-05-07    26.0               22.60
5       Max  Verstappen      6  2023-05-28    25.0               22.60
6       Max  Verstappen      7  2023-06-04    26.0               24.00
7       Max  Verstappen      8  2023-06-18    25.0               24.00
8       Max  Verstappen      9  2023-07-02    26.0               25.60
9       Max  Verstappen     10  2023-07-09    26.0               25.60
10      Max  Verstappen     11  2023-07-23    26.0               25.80
11      Max  Verstappen     12  2023-07-30    25.0               25.60
12      Max  Verstappen     13  2023-08-27    25.0               25.60
13      Max  Verstappen     14  2023-09-03    25.0               25.40
14      Max  Verstappen     15  2023-09-17    10.0               22.20
15      Max  Verstappen     16  2023-09-24    26.0               22.20
16      Max  Verstappen     17  2023-10-08    26.0               22.40
17      Max  Verstappen     18  2023-10-22    25.0               22.40
18      Max  Verstappen     19  2023-10-29    25.0               22.40
19      Max  Verstappen     20  2023-11-05    25.0               25.40
20      Max  Verstappen     21  2023-11-19    25.0               25.20
21      Max  Verstappen     22  2023-11-26    26.0               25.20

In [8]:
with open("../sql/analytics_queries/05_teammate_head_to_head.sql") as f:
    query = f.read()

h2h_df = pd.read_sql(text(query), engine)
h2h_df

,constructor_name,year,driver_a,driver_b,a_wins,b_wins,races_together
0,McLaren,2023,Lando Norris,Oscar Piastri,17,5,22
1,Red Bull,2023,Sergio Pérez,Max Verstappen,2,20,22
2,Alpine F1 Team,2023,Pierre Gasly,Esteban Ocon,11,11,22
3,Aston Martin,2023,Fernando Alonso,Lance Stroll,18,4,22
4,Ferrari,2023,Carlos Sainz,Charles Leclerc,10,12,22
5,Mercedes,2023,Lewis Hamilton,George Russell,15,7,22
6,Haas F1 Team,2023,Nico Hülkenberg,Kevin Magnussen,13,9,22
7,Alfa Romeo,2023,Valtteri Bottas,Guanyu Zhou,13,9,22
8,Williams,2023,Alexander Albon,Logan Sargeant,19,3,22
9,AlphaTauri,2023,Yuki Tsunoda,Nyck de Vries,8,2,10
10,AlphaTauri,2023,Daniel Ricciardo,Yuki Tsunoda,3,4,7
11,AlphaTauri,2023,Yuki Tsunoda,Liam Lawson,1,4,5