In [5]:
import sys, os
sys.path.append(os.path.abspath(".."))

%load_ext autoreload
%autoreload 2

import pandas as pd
pd.set_option('display.max_columns', None)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
from src.db import engine
from src.features import load_results_base, compute_rolling_form

base_df = load_results_base(engine)
print(f"Loaded {len(base_df)} rows")
base_df.head()

Loaded 26759 rows

,result_id,driver_key,forename,surname,constructor_key,constructor_name,race_key,year,round,race_date,grid,position_order,points,status
0,371,1,Lewis,Hamilton,1,McLaren,36,2007,1,2007-03-18,4,3,6.0,Finished
1,392,1,Lewis,Hamilton,1,McLaren,37,2007,2,2007-04-08,4,2,8.0,Finished
2,414,1,Lewis,Hamilton,1,McLaren,38,2007,3,2007-04-15,2,2,8.0,Finished
3,436,1,Lewis,Hamilton,1,McLaren,39,2007,4,2007-05-13,4,2,8.0,Finished
4,458,1,Lewis,Hamilton,1,McLaren,40,2007,5,2007-05-27,2,2,8.0,Finished

In [7]:
featured_df = compute_rolling_form(base_df)

verstappen_2023 = featured_df[
    (featured_df["surname"] == "Verstappen") & (featured_df["year"] == 2023)
][["round", "race_date", "points", "rolling_form_index"]]

verstappen_2023

       round   race_date  points  rolling_form_index
24970      1  2023-03-05    25.0               25.00
24971      2  2023-03-19    19.0               22.00
24972      3  2023-04-02    25.0               23.00
24973      4  2023-04-30    18.0               21.75
24974      5  2023-05-07    26.0               22.60
24975      6  2023-05-28    25.0               22.60
24976      7  2023-06-04    26.0               24.00
24977      8  2023-06-18    25.0               24.00
24978      9  2023-07-02    26.0               25.60
24979     10  2023-07-09    26.0               25.60
24980     11  2023-07-23    26.0               25.80
24981     12  2023-07-30    25.0               25.60
24982     13  2023-08-27    25.0               25.60
24983     14  2023-09-03    25.0               25.40
24984     15  2023-09-17    10.0               22.20
24985     16  2023-09-24    26.0               22.20
24986     17  2023-10-08    26.0               22.40
24987     18  2023-10-22    25.0               22.40
24988     19  2023-10-29    25.0               22.40
24989     20  2023-11-05    25.0               25.40
24990     21  2023-11-19    25.0               25.20
24991     22  2023-11-26    26.0               25.20